name: jason-moyer
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'Photographer / Creative Director '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#575757'
    - '#ffffff'
    - '#7e7e7e'
    - '#d1d1d1'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
