name: jason-moyer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92507
title: 'Photographer / Creative Director '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#434343'
    - '#939393'
    - '#fdfdfd'
    - '#d5d5d5'
  brandStrength: 1
  lightness: 0.9431065449025482
  saturation: 0
  rhythmicContrast: 0.6365862290840596
purpose: []
