name: jason-moyer
favicon: null
layout_spectrum: 0.052969651529565454
typography_spectrum: 0.973747156560421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.15890609589405358
  lightness: 0.9431065449025482
  saturation: 0.31015292718075216
  rhythmicContrast: 0.6365862290840596
purpose: []
