name: jason-moyer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05979
title: Design - Photography - Adventure
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#E2E2E2'
    - '#ACACAE'
    - '#8A898E'
    - '#3E3D4B'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
