name: jason-moyer
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: 'Photographer / Creative Director '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0cec3'
    - '#fe5833'
    - '#37252d'
    - '#6a5e60'
    - '#a03210'
  brandStrength: 0.0625
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
